### ISSUE TITLE
Auto SSL does not work correct for me

### ISSUE THREAD

**Issue by Chris53897** [dunglas/frankenphp-demo#13]
Mac M1.
A intermedia certificate gets created, but the browser (firefox and chrome tested), say that this is not a valid one.

The most import line in the log is probably `server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS`

`{"level":"info","ts":1692474817.7516222,"msg":"maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined"}
{"level":"info","ts":1692474817.7724752,"msg":"using provided configuration","config_file":"/etc/Caddyfile","config_adapter":""}
{"level":"warn","ts":1692474817.7732594,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/Caddyfile","line":3}
{"level":"info","ts":1692474817.7738304,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1692474817.7739658,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1692474817.7739768,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1692474817.7741318,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x4000033a80"}
{"level":"info","ts":1692474817.8361635,"msg":"FrankenPHP started 🐘","php_version":"8.2.9"}
{"level":"info","ts":1692474817.8363905,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1692474817.8364415,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"warn","ts":1692474817.8439717,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
{"level":"info","ts":1692474817.8441658,"msg":"define JAVA_HOME environment variable to use the Java trust"}
{"level":"info","ts":1692474817.8441718,"msg":"warning: \"certutil\" is not available, install \"certutil\" with \"apt install libnss3-tools\" or \"yum install nss-tools\" and try again"}
{"level":"info","ts":1692474818.4005547,"msg":"certificate installed properly in linux trusts"}
{"level":"info","ts":1692474818.4009395,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1692474818.401096,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
{"level":"info","ts":1692474818.4012878,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1692474818.4013226,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1692474818.4013844,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["localhost"]}
{"level":"info","ts":1692474818.4015412,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1692474818.4016128,"msg":"serving initial configuration"}
`

**Comment by dunglas** [comment]
It's intended. Locally a self-signed certificate is created in the container. Caddy isn't able to update the system bundle as it's outside the container. Just accept the TLS certificate in the browser.

**Comment by Chris53897** [comment]
Thanks for explanation. Can you please add a line in the readme? I can create a PR, but maybe it will take longer to find a suiteable wording, than just add this by youself.

**Comment by dunglas** [comment]
To be honest this belongs more in the Caddy docs or in Symfony Docker when it will switch to FrankenPHP.

**Comment by Chris53897** [comment]
ok, i will close this.
