### ISSUE TITLE
Caddyfile in root-folder is confusing

### ISSUE THREAD

**Issue by Chris53897** [dunglas/frankenphp-demo#14]
The Caddyfile is not used, and i guess a helper for development.
I think this is confusing, as user could believe that this is used in the demo.

https://github.com/dunglas/frankenphp-demo/blob/main/Caddyfile

Maybe we can rename the file, or add a comment in the file. Or remove it complety.

But at this could be needed for https://github.com/dunglas/frankenphp-demo/issues/13

**Comment by dunglas** [comment]
It's useful for dev and benchmarking, so adding a comment instead of removing it would be nice.
