### ISSUE TITLE
HTTP3 By default

### ISSUE THREAD

**Issue by Nayte91** [dunglas/frankenphp-demo#20]
Hello ! 

I tried your demo to see if frankenphp uses http3.
- Cloned repo,
- composer install,
- docker run \
    -e FRANKENPHP_CONFIG="worker ./public/index.php" \
    -v $PWD:/app \
    -p 80:80 -p 443:443 \
    dunglas/frankenphp
- use firefox 121 (note that it handles H3, as I see h3 request/responses when downloading fonts for example)

And on my network tab, everything is H2.

I tried to add udp to actual command:
```
docker run \
-e FRANKENPHP_CONFIG="worker ./public/index.php" \
-v $PWD:/app \
-p 80:80 -p 443:443/tcp -p 443:443/udp \
dunglas/frankenphp
```

And same results.

Do you know if something must be activated somewhere? Do you share this observation? 

Thank you for the good work!

**Comment by dunglas** [comment]
HTTP/3 uses UDP. You must expose the `443` port on UDP, not only on TCP.

Also, browsers usually start with HTTP/2 and switch to HTTP/3 only if a Alt-Svc header exists, so be sure that the browser does extra requests (like downloading assets).

**Comment by Nayte91** [comment]
Ooooh OK I understand what happens now.
- I tried with your symfony demo, then the html was served with http and there's no enough other requests to get your point.
- I tried with my own app with importmap-ed CSS and JS files and I can observe that they are subsequently served with HTTP3.

So experience is aligned on your theory, good job.

Thank you very much! ❤️
